[package]
name = "test-support"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test-support-server"
path = "src/bin/test-support-server.rs"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.8"
futures = "0.3"