[package]
name = "test-support"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
once_cell = "1.21"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.8"
futures = "0.3"
libc = "0.2"